### ISSUE TITLE
IP vetting for transition to ASL 2.0

### ISSUE THREAD

**Issue by hennejg** [levigo/jbig2-imageio#31]
In order to achieve #30, we need to vet the IP to this component. The vast majority of the component's code base is solely owned by levigo holding GmbH. However, there is one known contributor with an already merged change request and two pending pull requests. We need permission by those contributors for a transition to the ASL.

The following contributions from outside levigo need to be considered:

* PR #3 with commits fce4d3876a440305ecb643770e13b3dd9164ca38 and 4be6f1b01a1b537397a74d89e1869eea4373b839 provided by @dbdr has been merged.
* PR #28 provided by @janpe2 is currently pending
* PR #29 provided by @janpe2 is currently pending

So, to make the questions explicit and hopefully cause GitHub to notify the contributors:

* @janpe2 would you still be willing to provide your pending pull requests under the new ASL 2.0 license? If so, please let us know in a comment.
* @dbdr would you be willing to give us permission to release your changes under the ASL 2.0? If so, please let us know in a comment.

**Comment by dbdr** [comment]
I give you permission to release my changes under the ASL 2.0.

**Comment by hennejg** [comment]
Browsing though the contributions I noticed a contribution by @THausherr in #21. But since you are already an ASF committer and we intend to move this component under the PDFBox umbrella, I suppose that you agreeing to the license change is just a formality. Correct?

**Comment by THausherr** [comment]
(2nd attempt, mail got lost)

Of course I agree.

But the PR in that issue wasn't by me. Re: The PDF file I attached (584334-JBig2-p1.pdf), I don't have the copyright for it. However I doubt that this page has a copyright at all:
https://en.wikipedia.org/wiki/Copyright_law_of_the_United_States#Works_subject_to_copyright_law
The United States copyright law protects "original works of authorship".

That page is just some boring cover page and its title isn't poetry or anything similarly great. I got the file from the digitalcorpora site: "For these reasons, we have created and released a corpus of 1 million documents that are freely available for research and may be (to the best of our knowledge) freely redistributed. These documents were obtained by performing searches for words randomly chosen from the Unix dictionary, numbers randomly chosen between 1 and 1 million, and randomized combinations of the two, for documents of specified file types that resided on web servers in the .gov domain using the Yahoo an Google search engines."

If you still think you can't use that file, you can delete it, because it is only useful for tests.

**Comment by hennejg** [comment]
@THausherr thanks! My concerns were less about the test document but the code fragment you contributed via the comment on #21.

**Comment by THausherr** [comment]
That is of course fine, too.

**Comment by janpe2** [comment]
I can provide my pending pull requests under ASL 2.0.

**Comment by hennejg** [comment]
@janpe2 thanks a lot!

**Comment by hennejg** [comment]
With this I conclude that all contributors have agreed to a license change to ASL 2.0.
